NNPDF/eko

benchmarks/ekobox/benchmark_evol_pdf.py, src/ekobox/evol_pdf.py
Solve #130 
The bug was due to the fact that, even if `all_blocks` was supposed to contain all and only the blocks of a certain replica, it was not initialized to zero at the beginning of each loop step on `evolved_PDFs`.
=> Fixing bug of ekobox evolve_pdfs with multiple replicas

src/eko/runner.py, tests/eko/test_runner.py
We want to massively simplify `runnner.py`:
- In `get_output` we want to avoid the rotations: if needed they should be done afterwards. 
- In `__init__ ` we just need to skip the last part in which `targetpids`, `inputpids`, `targetgrid` and `inputgrid` are collected.
@felixhekhorn @AleCandido
=> Refactor runner

src/eko/io/struct.py
As @andreab1997 found out [`base64.b64encode`](https://docs.python.org/3/library/base64.html?highlight=base64#base64.b64encode) is not safe for usage with filesystem operations due to the presence of `/` in the default base64 alphabet, but [`base64.urlsafe_b64encode`](https://docs.python.org/3/library/base64.html?highlight=base64#base64.urlsafe_b64encode) is
=> Use filesystem safe b64

pyproject.toml
as said was simply missing and thus rtd was failing
=> Add ekore in pyproject.toml

src/ekobox/info_file.py
It seems that after the QED PR was merged (cc @niclaurenti ) we forgot to add the -1 here. If you know other places in which we may have forgotten, please comment here and I will fix. @felixhekhorn @AleCandido 
@giacomomagni I tag you because this is related to the issue you opened for `evolven3fit_new`.
=> Add -1 to QCD order in info file

benchmarks/lha_paper_bench.py, doc/source/code/IO.rst, src/eko/io/runcards.py, src/ekomark/benchmark/external/LHA_utils.py, src/ekomark/navigator/navigator.py, tests/eko/io/test_runcards.py
Closes #237 
This PR fixes
- #237 and adds the relevant test
- a inconsistent translation of `mu2grid` -> `mugrid` in LHA
- the output of `flavored_mugrid` to be serializable and adds the relevant test
- left-over `Q2grid` in LHA benchmark
- left-over `Q2grid` in navigator
- left-over `Q2grid` in docs
further comments:
- #237 also affects [yadism](https://github.com/NNPDF/yadism/blob/9617329a4025a27ac6de99c0ba904e276fcb8dfb/src/yadism/output.py#L99) of course
- the current implementation looses track of `QrefQED` since there is no such thing any longer - what should we do? should we translate the existence to `couplings.em_running`? should we change the theory again? (meaning `banana`)
- by creating this PR we can test the trigger for #227
=> Fix IO for LHA bot

src/ekobox/info_file.py
Currently the `NumFlavors` written by eko in the `info` file correspond to the number of possible partons, while this field is actually the maximum `nf` used for the evolution of `alpha_s`.
Ref: https://lhapdf.hepforge.org/config.html
=> Write the right `nf` in the LHAPDF `.info` file.

benchmarks/CT14_bench.py, benchmarks/CT18_bench.py, benchmarks/HERA20_bench.py, benchmarks/NNPDF_bench.py, benchmarks/apfel_bench.py, benchmarks/lha_paper_bench.py, benchmarks/pegasus_bench.py, benchmarks/sandbox.py, doc/source/code/IO.rst, poetry.lock, pyproject.toml, src/eko/io/runcards.py, src/eko/quantities/heavy_quarks.py, src/ekomark/benchmark/external/apfel_utils.py, src/ekomark/benchmark/external/pegasus_utils.py, src/ekomark/benchmark/runner.py, tests/eko/io/test_runcards.py, tests/eko/kernels/test_ns.py, tests/eko/runner/test_parts.py
Fixing apfel benchmarks. Tomorrow I will run also the other benchmarks to see if they are broken or not
=> Fix apfel benchmarks

src/eko/basis_rotation.py, src/eko/evolution_operator/__init__.py, src/eko/evolution_operator/flavors.py, src/eko/evolution_operator/matching_condition.py, src/eko/evolution_operator/physical.py, src/eko/kernels/non_singlet.py, src/eko/kernels/non_singlet_qed.py, src/eko/member.py, src/ekobox/apply.py, src/ekore/anomalous_dimensions/unpolarized/space_like/__init__.py, src/ekore/anomalous_dimensions/unpolarized/space_like/as4/__init__.py, tests/eko/evolution_operator/test_flavors.py, tests/eko/evolution_operator/test_init.py, tests/eko/evolution_operator/test_matching_condition.py, tests/eko/evolution_operator/test_physical.py, tests/eko/kernels/test_kernels_QEDns.py, tests/eko/kernels/test_kernels_QEDsinglet.py, tests/eko/kernels/test_kernels_QEDvalence.py, tests/eko/test_basis_rotation.py, tests/ekore/anomalous_dimensions/unpolarized/space_like/test_init.py
reopening #311 after rebasing master
=> Interface QED and N3LO, n.2

src/eko/io/runcards.py, src/eko/runner/legacy.py, src/eko/runner/parts.py, tests/eko/runner/test_parts.py
=> address issue #322

src/eko/io/runcards.py, src/eko/runner/parts.py
Hot fix for matching order setting.
It should be properly tested, but if merging this is urgent we can postpone it.
=> Enforce default for matching order at post-init time

src/eko/couplings.py
just to have a second pair of eyes - do you see anything obvious on top?
=> Update couplings docs

src/ekore/anomalous_dimensions/unpolarized/time_like/as3.py
It appears I had made a mistake when reimplementing this code from https://github.com/vbertone/MELA/blob/master/src/evolution/andim_nnlo_tl.f#L117-118. It is now fixed. 
The ref in Vogt's code has this eqn which matches our definition of Mellin transform: 
so with this, I think everything is consistent.
=> fixing the condition from #263

src/ekore/operator_matrix_elements/unpolarized/space_like/as3/agg.py, tests/ekore/operator_matrix_elements/unpolarized/space_like/test_as3.py
in this PR I'd like to make the $a_{gg,Q}^{(3)}$ parametrization to have a easier and compact form in `x-space`, 
such that can be easily digest alo in that case. 
As visible in the two plots below, the new parametrization is equivalent to the previous one.
Relative difference in linear scale:
[aggQ3_rel_diff.pdf](https://github.com/NNPDF/eko/files/14555988/aggQ3_rel_diff.pdf)
Comparison in log scale:
[aggQ3_diff.pdf](https://github.com/NNPDF/eko/files/14555989/aggQ3_diff.pdf)
This parametrization can be shared easily with the MSHT people.
=> Add a nicer parametrization of aggQ3

src/eko/mellin.py, src/ekobox/evol_pdf.py, tests/eko/evolution_operator/test_init.py
Here we change the `r` parameter regulating the Talboth path, to make the large-x integration smoother. 
@scarlehoff
=> Fix large-x wiggles 

benchmarks/ekore/benchmark_pegasus_ad_us_as2.py, benchmarks/ekore/benchmark_pegasus_mellin.py, benchmarks/ekore/benchmark_pegasus_ome_ps_as2.py
@igborsa is it okay if I copy your implementation of the polarized NNLO OME here?
As will be visible in the CI the benchmark fails in the last line - commenting that line out, we pass
The error will be
```
E           AssertionError: 
E           Not equal to tolerance rtol=1e-07, atol=0
E           hg,N=2
E           Mismatched elements: 1 / 1 (100%)
E           Max absolute difference: 0.2584379
E           Max relative difference: 0.02809631
E            x: array(-9.456725+0.j)
E            y: array(-9.198287)
```
=> Add ome.ps.as2 benchmark vs. Pegasus

.github/workflows/unittests-rust.yml, .github/workflows/unittests.yml, README.md, pyproject.toml, pyproject.toml.patch
=> Add Rust unit tests to CI

src/ekobox/evol_pdf.py, src/ekobox/info_file.py, src/ekobox/utils.py, tests/ekobox/test_evol_pdf.py, tests/ekobox/test_info_file.py
The information about nf is not utilized when generating the info files. This PR fixes that.
evolven3fit relies on eko for the info file so once this is merged into a release of eko it should work fine.
Apparently LHAPDF doesn't have a block mechanism for `alpha_s` so at the moment we just provide two values for two nfs for the same Q at the thresholds.
(As far as I can see, the same problem was there in NNPDF4.0 -apfel + evolven3fit- and NNPDF3.1 -apfel + evolvennfit-, so nobody ever noticed...)
=> Use nf to generate alpha_s

benchmarks/eko/benchmark_inverse_matching.py, src/ekobox/apply.py, src/ekobox/evol_pdf.py, src/ekomark/benchmark/runner.py, tests/ekobox/test_apply.py, tests/ekobox/test_evol_pdf.py
Closes #408 
1. As said in the issue this is basically just changing the `einsum` instructions, which are now `"ajbk,rbk->raj"`.
2. @giacomomagni, @scarlehoff, @Radonirinaunimi  can you please help me and check if that is what you need on the other side? i.e. can someone of you please provide the `evolven3fit` side? :innocent: 
3. the current state _only_ changes the "apply" methods: it provides a new low-level callable `apply.apply_grids`, which accepts an EKO and a 3D tensor sorted `(replica, flavor, xgrid)`, which is hopefully what you wanted.
4. it _does not_ provide new `genpdf` utilities, as the writing of replica has to be done replica by replica. Actually now I wonder, if the performance bottleneck is/was really the EKO contraction, or is it rather the writing of the LHAPDF files? …
=> Rework ekobox.apply

CHANGELOG.md, src/eko/evolution_operator/__init__.py, src/eko/evolution_operator/quad_ker.py, src/eko/kernels/non_singlet.py, src/eko/kernels/singlet.py, tests/eko/evolution_operator/test_init.py, tests/eko/kernels/test_ns.py, tests/eko/scale_variations/test_diff.py, tests/eko/scale_variations/test_expanded.py
Closes #447 
As a consequence `ev_op_iterations` also dropped from `kernels.ns.dispatcher`, i.e. in the non-singlet sector there is no iteration anywhere (since exact _is_ exact). This triggers a few more changes on the testing side.
=> Remove `ev_op_iterations` from truncated
